### PR TITLE
PHP Storm project files

### PR DESCRIPTION
**Pull request by mecha**
Adds PHP Storm project files and incorporates a solution for #24

### CODE REVIEW

**Comment by XedinUnknown** [comment]
@mecha, `misc.xml` doesn't appear to be relevant, because it looks like a UI config. Can you kindly confirm?

**Comment by mecha** [comment]
Yes it is. I forgot about it. Will remove.

**Comment by XedinUnknown** [comment]
Kemm inti verifajt.

**Comment by mecha** [comment]
@XedinUnknown Removed.

**Pull request merged**
