### PR TITLE
Version 0.2

### PR DESCRIPTION
**Pull request by XedinUnknown**
Major improvements and bugfixes.

- Test templates improved, fixed, and standardized.
- Added Dhii badge to README template.
- Remote is deduced automatically from vendor and folder name combination.
- Fixed bootstrapped project failing to build on PHP < 5.6.
- Using stable version of CS fixer standard config.
- No longer targeting PHP 5.3.
- Fixed bug with project files missing.

### CODE REVIEW

**Comment by XedinUnknown** [comment]
#20 needs to be fixed before this is merged. Fed up with that unconfigurable rule. It creates the necessity for a lot of extra work.

**Comment by XedinUnknown** [comment]
@mecha, if you do #21, I will merge this :D

**Comment by mecha** [comment]
You're just gonna keep on adding more work? Fine, I'll do it 😆

**Comment by XedinUnknown** [comment]
Just doesn't feel right to make a second release without an explanation of what this is for.

**Comment by XedinUnknown** [comment]
LGTM.

**Pull request merged**
